name: Website Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

# Serialize builds on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  images:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - uses: abatilo/actions-poetry@v4
        with:
          poetry-version: '2.4.1'
    
      - name: Install Dependencies
        run: poetry install

      - name: Generate Webpages and Images
        run: poetry run python scripts/automate.py

      - name: Build Webpages with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: docs/
          destination: docs/_site
          token: ${{ secrets.GITHUB_TOKEN }}

      # Don't rebuild the website when changes are pushed to gh-pages branch
      # since that branch contains the built HTML pages. Also, make sure
      # the CNAME is in the gh-pages branch
      - name: Add .nojekyll and CNAME
        run: |
          sudo touch docs/_site/.nojekyll
          sudo cp docs/CNAME docs/_site/

      # Push the changes to the gh-pages branch
      - name: Publish Site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_site
          token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}
